twig:
    default_path: '%kernel.project_dir%/src/App/ApiBundle/Resources/views'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@SonataCore/Form/datepicker.html.twig'
